[versions]
# Annotations
findbugs = "3.0.2"

# Gradle plugins
licenser = "0.6.1"
nexus = "1.1.0"

[libraries]
# Annotations
findbugs = { group = "com.google.code.findbugs", name = "jsr305", version.ref = "findbugs" }

[plugins]
licenser = { id = "org.cadixdev.licenser", version.ref = "licenser" }
nexus = { id = "io.github.gradle-nexus.publish-plugin", version.ref = "nexus" }
